### ISSUE TITLE
[Suggestion] Support wezterm directly

### ISSUE THREAD

**Issue by vihu** [catppuccin/wezterm#6]
Hello, thank you for your excellent color schemes. I primarily use wezterm and thought it would be preferable to add support for catppuccin directly in wezterm. To that end I have opened a [PR](https://github.com/wez/wezterm/pull/2221) for wezterm. Would be helpful if you could also review :slightly_smiling_face:

**Comment by vihu** [comment]
Nevermind, I was told to open a PR for iterm2 since that's where the colorschemes for wezterm actually reside.

**Comment by nekowinston** [comment]
Will you go ahead and open a MR on iTerm2? I'd be happy to review it.

**Comment by wez** [comment]
I was just looking at this because someone mentioned it on twitter.

I've recently overhauled how wezterm pulls in colorschemes and I can now easily pull in the data using the iterm2 color scheme formatted data from the iterm repo; I have some code ready to commit that will do that.  (Previously, we could only use the iterm2 color scheme repo as the source).

Looking through this repo it appears as though the lua code in here sets additional colors.
I can't use this repo as the source because it uses executable lua code that might have unexpected side effects and I cannot "risk" evaluating that in places where I might have eg: code signing credentials.

Are the additional colors important for the highest fidelity representation of this color scheme?

If the answer is no then I can commit my pending iterm2 based sync logic.
If the answer is yes, could the lua files be rephrased as wezterm toml files and committed here?
While the docs don't say it, wezterm's toml files do also support setting all of the things that can go in the `colors` portion of the wezterm config.

**Comment by nekowinston** [comment]
👋 Hi there! Thanks a bunch for your lovely work on WezTerm! ❤️ 

I absolutely understand the hesitancy to include the lua code.

Do you mean the 4 variations defined [here](https://github.com/catppuccin/wezterm/blob/65078e846c8751e9b4837a575deb0745f0c0512f/catppuccin.lua#L3-L117), or the [indexed](https://github.com/catppuccin/wezterm/blob/65078e846c8751e9b4837a575deb0745f0c0512f/catppuccin.lua#L177-L180) colours?
The first isn't necessary, we could provide 4 files instead, such as `Catppuccin-mocha.toml`, `Catppuccin-macchiato.toml`, etc.
The latter, `indexed` colours, are according to our style guide.

I'd be happy to provide the colourscheme in TOML format, if this helps with including it as a default. 👍

**Comment by wez** [comment]
This whole block isn't typically part of a color scheme:
https://github.com/catppuccin/wezterm/blob/65078e846c8751e9b4837a575deb0745f0c0512f/catppuccin.lua#L152-L184

Indexed colors are documented as supported in https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

Technically speaking, you could put the rest of those in the block I highlighted in the TOML file as well, but no other scheme does that so far. I've been resisting making an official ruling on whether that is good or not because the color scheme/palette is theoretically a per-pane attribute and I don't know if a scheme should unilaterally apply to the tab bar: it could get weird if two panes have different schemes.  I'm willing to give it a go with this scheme and see how things play out though!

**Comment by wez** [comment]
BTW: I've expanded the colorscheme file to include a metadata section where you can include the scheme name and author.
https://wezfurlong.org/wezterm/config/lua/wezterm.color/save_scheme.html shows an example of how that looks at the bottom.

Using the name metadata would allow you to name the scheme something like "Catppuccin Latte" with whatever spaces/capitalization you'd prefer, rather than having the name be derived from the filename.

**Comment by wez** [comment]
slightly OT: I saw that you're associated with https://farbenfroh.io/faerber. Some of the recent commits to wezterm are in support of similar stuff: [extract_colors_from_image](https://wezfurlong.org/wezterm/config/lua/wezterm.color/extract_colors_from_image.html) and a [color object](https://wezfurlong.org/wezterm/config/lua/color/index.html) for computing colors.

**Comment by nekowinston** [comment]
>  I've been resisting making an official ruling on whether that is good or not because the color scheme/palette is theoretically a per-pane attribute and I don't know if a scheme should unilaterally apply to the tab bar: it could get weird if two panes have different schemes. I'm willing to give it a go with this scheme and see how things play out though!

It's great to hear you're willing to give us a shot!
When I initially ported this theme to our new flavours, the main goal was to replicate the [Kitty port](https://github.com/catppuccin/kitty) as closely as possible. I've also been [trying to replicate](https://gist.github.com/abe7d7a7a0ab19c69747bdc79cf15ede) the tab bar in a similar manner, and have thought about including the config for that in our README.
![wezterm-mocha](https://user-images.githubusercontent.com/79978224/179316063-e44e2f7d-7e0a-4edc-b5c0-51384a38360d.png)

That being said, those upcoming TOML files meant for the inclusion, will obviously not include these kinds of more invasive tweaks.

> I've expanded the colorscheme file to include a metadata section where you can include the scheme name and author.

Great to know, thanks!

I'll get to work creating the TOML ports then. 🙂 

> slightly OT: I saw that you're associated with [farbenfroh.io/faerber](https://farbenfroh.io/faerber)

Very cool, looking forward to trying out those new features in WezTerm! 🎉

**Comment by wez** [comment]
If you're running the nightly build of wezterm, you could run with your lua based scheme config from this repo, then pop open the debug overlay (CTRL-SHIFT-L) to get a lua repl and then do something like:

```lua
> wezterm.colors.save_scheme(catppuccin.select(something), {name="Catppucin Latte", author="someone"}, "/tmp/latte.toml")
```

to get a first pass at a TOML version without too much sweat

**Comment by wez** [comment]
Also, as a "pro tip", functions you define in wezterm.lua can also be called from the debug overlay repl

**Comment by wez** [comment]
Needed a little fix to allow exporting indexed colors; once that builds out (takes about an hour to build for all platforms), you can use a nightly build and:

```lua
> wezterm.color.save_scheme(CAT.setup{}, {}, "/tmp/cat.toml")
```

produces:

```toml
[colors]
ansi = [
    '#45475a',
    '#f38ba8',
    '#a6e3a1',
    '#f9e2af',
    '#89b4fa',
    '#f5c2e7',
    '#94e2d5',
    '#bac2de',
]
background = '#1e1e2e'
brights = [
    '#585b70',
    '#f38ba8',
    '#a6e3a1',
    '#f9e2af',
    '#89b4fa',
    '#f5c2e7',
    '#94e2d5',
    '#a6adc8',
]
compose_cursor = '#f2cdcd'
cursor_bg = '#f5e0dc'
cursor_border = '#f5e0dc'
cursor_fg = '#11111b'
foreground = '#cdd6f4'
scrollbar_thumb = '#585b70'
selection_bg = '#585b70'
selection_fg = '#cdd6f4'
split = '#6c7086'
visual_bell = '#313244'

[colors.indexed]
16 = '#fab387'
17 = '#f5e0dc'

[colors.tab_bar]
background = '#1e1e2e'
inactive_tab_edge = '#575757'
inactive_tab_edge_hover = '#363636'

[colors.tab_bar.active_tab]
bg_color = '#585b70'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1e1e2e'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#585b70'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1e1e2e'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#585b70'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
```
